kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - go build
  - go test
  settings:
    # registry: docker.io
    repo: pavansa/dronya
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
